before_script:
  - apt-get update -qq && apt-get install -y -qq build-essential libssl-dev
  - curl https://raw.githubusercontent.com/creationix/nvm/v0.25.0/install.sh | bash
  - source ~/.profile
  - nvm --version
  - nvm install 0.10

lint:
  script: "npm run jslint"

test:
  script: "npm test"
