language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libprotobuf-dev
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - grep -R '\.only' test; [[ ! $? -eq 0 ]]
  - npm run lint
  - npm run compile
  - npm test
branches:
  only:
    - master
